Feature/import file to sqs
pagopa/pn-troubleshooting pull request #166
Opened 2024-09-25 08:51 UTC by vincenzo-racca-pa

2024-10-03 15:19 UTC, vincenzo-racca-pa commented on from-file-to-sqs/libs/AwsClientWrapperWithRegion.js
> +
Per ora manterrei questo approccio per non intaccare gli altri script, anche se non si dovrebbe rompere nulla. Questo refactoring lo farei quando utulizzeremo in tutti gli script il wrapper di AWS di pn-commons (vedo che in molti script quel file js è copiato)

2024-10-04 08:21 UTC, ViVeniero requested changes

2024-10-04 08:41 UTC, vincenzo-racca-pa commented on dump_sqs_with_delete/dump_sqs_with_delete.js
> +    { name: "deleteMode", mandatory: false, subcommand: [] }
fatto

2024-10-04 10:22 UTC, ViVeniero approved these changes

2024-10-04 10:24 UTC, merged