feature: PN-13489: aggiunta indicizzazione parquet di pn-Action
pagopa/pn-troubleshooting pull request #193
Opened 2024-12-09 19:18 UTC by marco-vit-pagopa

2024-12-09 20:04 UTC, fdammassa requested changes

2024-12-09 20:04 UTC, fdammassa commented on bi_or_not_bi__ec_metadata/src/main/resources/dynamo_export_indexing_queries.sql
> +      get_json_object(json_string, '$.Item.type.S') as type
@marco-vit-pagopa Sarebbe il caso di aggiungere "logicalDeleted@?

https://github.com/pagopa/pn-delivery-push/blob/develop/functions/action-enqueuer/src/app/eventHandler.js#L25-L28

2024-12-10 10:13 UTC, fdammassa approved these changes

2024-12-10 11:04 UTC, marco-vit-pagopa commented on bi_or_not_bi__ec_metadata/src/main/resources/dynamo_export_indexing_queries.sql
> +      get_json_object(json_string, '$.Item.type.S') as type
Si, è il caso. 
L'ho aggiunto.

2024-12-10 13:32 UTC, merged